&MATL ID                    = 'FABRIC'
      FYI                   = 'Properties completely fabricated'
      SPECIFIC_HEAT         = 1.0
      CONDUCTIVITY          = 0.1
      DENSITY               = 100.0
      N_REACTIONS           = 1
      NU_SPEC               = 1.
      SPEC_ID               = 'PROPANE'
      REFERENCE_TEMPERATURE = 320.
      HEAT_OF_REACTION      = 3000.
      HEAT_OF_COMBUSTION    = 15000. /

&MATL ID                    = 'FOAM'
      FYI                   = 'Properties completely fabricated'
      SPECIFIC_HEAT         = 1.0
      CONDUCTIVITY          = 0.05
      DENSITY               = 40.0
      N_REACTIONS           = 1
      NU_SPEC               = 1.
      SPEC_ID               = 'PROPANE'
      REFERENCE_TEMPERATURE = 320.
      HEAT_OF_REACTION      = 1500.
      HEAT_OF_COMBUSTION    = 30000. /

&SURF ID             = 'UPHOLSTERY'
      FYI            = 'Properties completely fabricated'
      COLOR          = 'PURPLE'
      BURN_AWAY      = .TRUE.
      MATL_ID(1:2,1) = 'FABRIC','FOAM'
      THICKNESS(1:2) = 0.002,0.1  /
