function [NVERT,INOD]=INSERT_FACE_VERT(XYZV,NM,CEI,NVERT)

global IAXIS JAXIS KAXIS GEOMEPS MESHES

for INOD=1:NVERT
   if( abs(XYZV(IAXIS)-MESHES(NM).CUT_EDGE(CEI).XYZVERT(IAXIS,INOD)) > GEOMEPS ); continue; end
   if( abs(XYZV(JAXIS)-MESHES(NM).CUT_EDGE(CEI).XYZVERT(JAXIS,INOD)) > GEOMEPS ); continue; end
   if( abs(XYZV(KAXIS)-MESHES(NM).CUT_EDGE(CEI).XYZVERT(KAXIS,INOD)) > GEOMEPS ); continue; end
   return
end
NVERT = NVERT + 1;
INOD  = NVERT;
MESHES(NM).CUT_EDGE(CEI).XYZVERT(IAXIS:KAXIS,INOD) = XYZV(IAXIS:KAXIS);

return