$RUNSMV Controls activate_vents
$RUNSMV Detectors beam_detector
$RUNSMV Fires room_fire
$RUNSMV Flowfields helium_2d
$RUNSMV Flowfields sawtooth
$RUNSMV Flowfields symmetry_test
$RUNSMV Flowfields jet_fan
$RUNSMV HVAC HVAC_mass_conservation
$RUNSMV HVAC HVAC_energy_pressure
$RUNSMV HVAC leak_test_2
$RUNSMV Miscellaneous pyramid
$RUNSMV NS_Analytical_Solution ns2d_64
$RUNSMV Pressure_Effects pressure_boundary
$RUNSMV Pressure_Solver dancing_eddies
$RUNSMV Scalar_Analytical_Solution  move_slug
$RUNSMV Scalar_Analytical_Solution  move_slug_fl1
$RUNSMV Species Propane_flame_deposition
$RUNSMV Sprinklers_and_Sprays cascade
$RUNSMV Turbulence csmag_64
$RUNSMV Turbulence dsmag_64
$RUNSMV Visualization objects_static
$RUNSMV Visualization objects_dynamic
