% McDermott
% 2-24-10
% sandia_methane_fire.m
%
% Plot Sandia 1m methane pool fire data and FDS results

close all
clear all

addpath '..\..\Validation\Sandia_Plumes\Experimental_Data'
addpath '..\..\Validation\Sandia_Plumes\FDS_Output_Files'

% vertical velocity

radial_profile('Sandia_Plumes\Sandia_CH4_1m_W_zp3',[2:22],0.0, ...
               'Radial Position (m)','Vertical Velocity (m/s)','Sandia Methane Pool Fire','$z = 0.3$ m','Northeast', ...
               -.5,.5,.05,-.5,.5,.1,0,8,1, ...
               'Sandia_CH4_1m_W_zp3.csv','ko','Exp') %, ...
               %'Sandia_He_1m_dx3cm_devc.csv','k--','FDS 3 cm', ...
               %'Sandia_He_1m_dx1p5cm_devc.csv','k-','FDS 1.5 cm')
           
radial_profile('Sandia_Plumes\Sandia_CH4_1m_W_zp5',[2:22],0.0, ...
               'Radial Position (m)','Vertical Velocity (m/s)','Sandia Methane Pool Fire','$z = 0.5$ m','Northeast', ...
               -.5,.5,.05,-.5,.5,.1,0,8,1, ...
               'Sandia_CH4_1m_W_zp5.csv','ko','Exp') %, ...
               %'Sandia_He_1m_dx3cm_devc.csv','k--','FDS 3 cm', ...
               %'Sandia_He_1m_dx1p5cm_devc.csv','k-','FDS 1.5 cm')
               
radial_profile('Sandia_Plumes\Sandia_CH4_1m_W_zp9',[2:22],0.0, ...
               'Radial Position (m)','Vertical Velocity (m/s)','Sandia Methane Pool Fire','$z = 0.9$ m','Northeast', ...
               -.5,.5,.05,-.5,.5,.1,0,8,1, ...
               'Sandia_CH4_1m_W_zp9.csv','ko','Exp') %, ...
               %'Sandia_He_1m_dx3cm_devc.csv','k--','FDS 3 cm', ...
               %'Sandia_He_1m_dx1p5cm_devc.csv','k-','FDS 1.5 cm')
              
% radial velocity

radial_profile('Sandia_Plumes\Sandia_CH4_1m_U_zp3',[2:22],0.0, ...
               'Radial Position (m)','Radial Velocity (m/s)','Sandia Methane Pool Fire','$z = 0.3$ m','Northeast', ...
               -.5,.5,.05,-.5,.5,.1,-1,1,.2, ...
               'Sandia_CH4_1m_U_zp3.csv','ko','Exp') %, ...
               %'Sandia_He_1m_dx3cm_devc.csv','k--','FDS 3 cm', ...
               %'Sandia_He_1m_dx1p5cm_devc.csv','k-','FDS 1.5 cm')
           
radial_profile('Sandia_Plumes\Sandia_CH4_1m_U_zp5',[2:22],0.0, ...
               'Radial Position (m)','Radial Velocity (m/s)','Sandia Methane Pool Fire','$z = 0.5$ m','Northeast', ...
               -.5,.5,.05,-.5,.5,.1,-1,1,.2, ...
               'Sandia_CH4_1m_U_zp5.csv','ko','Exp') %, ...
               %'Sandia_He_1m_dx3cm_devc.csv','k--','FDS 3 cm', ...
               %'Sandia_He_1m_dx1p5cm_devc.csv','k-','FDS 1.5 cm')
               
radial_profile('Sandia_Plumes\Sandia_CH4_1m_U_zp9',[2:22],0.0, ...
               'Radial Position (m)','Radial Velocity (m/s)','Sandia Methane Pool Fire','$z = 0.9$ m','Northeast', ...
               -.5,.5,.05,-.5,.5,.1,-1,1,.2, ...
               'Sandia_CH4_1m_U_zp9.csv','ko','Exp') %, ...
               %'Sandia_He_1m_dx3cm_devc.csv','k--','FDS 3 cm', ...
               %'Sandia_He_1m_dx1p5cm_devc.csv','k-','FDS 1.5 cm')








