% McDermott
% 2-15-10
% sandia_helium_plume.m
%
% Plot Sandia 1m helium plume data and FDS results

close all
clear all

addpath '../../Validation/Sandia_Plumes/Experimental_Data'
addpath '../../Validation/Sandia_Plumes/FDS_Output_Files'

% vertical velocity

radial_profile('Sandia_Plumes/Sandia_He_1m_W2','row',[2:22],0.2,'relative',10, ...
               'Radial Position (m)','Vertical Velocity (m/s)','Sandia Helium Plume','$z = 0.2$ m','Northeast', ...
               -.5,.5,.05,-.5,.5,.1,0,5,1, ...
               'Sandia_He_1m_W_zp2.csv','ko','Exp', ...
               'Sandia_He_1m_dx3cm_devc.csv','k--','FDS 3 cm', ...
               'Sandia_He_1m_dx1p5cm_devc.csv','k-','FDS 1.5 cm')
           
radial_profile('Sandia_Plumes/Sandia_He_1m_W4','row',[23:43],0.2,'relative',10, ...
               'Radial Rosition (m)','Vertical Velocity (m/s)','Sandia Helium Plume','$z = 0.4$ m','Northeast', ...
               -.5,.5,.05,-.5,.5,.1,0,5,1, ...
               'Sandia_He_1m_W_zp4.csv','ko','Exp', ...
               'Sandia_He_1m_dx3cm_devc.csv','k--','FDS 3 cm', ...
               'Sandia_He_1m_dx1p5cm_devc.csv','k-','FDS 1.5 cm')

radial_profile('Sandia_Plumes/Sandia_He_1m_W6','row',[44:64],0.2,'relative',10, ...
               'Radial Position (m)','Vertical Velocity (m/s)','Sandia Helium Plume','$z = 0.6$ m','Northeast', ...
               -.5,.5,.05,-.5,.5,.1,0,5,1, ...
               'Sandia_He_1m_W_zp6.csv','ko','Exp', ...
               'Sandia_He_1m_dx3cm_devc.csv','k--','FDS 3 cm', ...
               'Sandia_He_1m_dx1p5cm_devc.csv','k-','FDS 1.5 cm')
           
% radial velocity

radial_profile('Sandia_Plumes/Sandia_He_1m_U2','row',[65:85],0.4,'relative',10, ...
               'Radial Position (m)','Radial Velocity (m/s)','Sandia Helium Plume','$z = 0.2$ m','Northeast', ...
               -.5,.5,.05,-.5,.5,.1,-1,1,.25, ...
               'Sandia_He_1m_U_zp2.csv','ko','Exp', ...
               'Sandia_He_1m_dx3cm_devc.csv','k--','FDS 3 cm', ...
               'Sandia_He_1m_dx1p5cm_devc.csv','k-','FDS 1.5 cm')
           
radial_profile('Sandia_Plumes/Sandia_He_1m_U4','row',[86:106],0.4,'relative',10, ...
               'Radial Position (m)','Radial Velocity (m/s)','Sandia Helium Plume','$z = 0.4$ m','Northeast', ...
               -.5,.5,.05,-.5,.5,.1,-1,1,.25, ...
               'Sandia_He_1m_U_zp4.csv','ko','Exp', ...
               'Sandia_He_1m_dx3cm_devc.csv','k--','FDS 3 cm', ...
               'Sandia_He_1m_dx1p5cm_devc.csv','k-','FDS 1.5 cm')
           
radial_profile('Sandia_Plumes/Sandia_He_1m_U6','row',[107:127],0.4,'relative',10, ...
               'Radial Position (m)','Radial Velocity (m/s)','Sandia Helium Plume','$z = 0.6$ m','Northeast', ...
               -.5,.5,.05,-.5,.5,.1,-1,1,.25, ...
               'Sandia_He_1m_U_zp6.csv','ko','Exp', ...
               'Sandia_He_1m_dx3cm_devc.csv','k--','FDS 3 cm', ...
               'Sandia_He_1m_dx1p5cm_devc.csv','k-','FDS 1.5 cm')
           
% helium mass fraction

radial_profile('Sandia_Plumes/Sandia_He_1m_YHe2','row',[128:148],0.3,'relative',10, ...
               'Radial Position (m)','Helium Mass Fraction','Sandia Helium Plume','$z = 0.2$ m','Northeast', ...
               -.5,.5,.05,-.5,.5,.1,0,1,.2, ...
               'Sandia_He_1m_YHe_zp2.csv','ko','Exp', ...
               'Sandia_He_1m_dx3cm_devc.csv','k--','FDS 3 cm', ...
               'Sandia_He_1m_dx1p5cm_devc.csv','k-','FDS 1.5 cm')
           
radial_profile('Sandia_Plumes/Sandia_He_1m_YHe4','row',[149:169],0.4,'relative',10, ...
               'Radial Position (m)','Helium Mass Fraction','Sandia Helium Plume','$z = 0.4$ m','Northeast', ...
               -.5,.5,.05,-.5,.5,.1,0,1,.2, ...
               'Sandia_He_1m_YHe_zp4.csv','ko','Exp', ...
               'Sandia_He_1m_dx3cm_devc.csv','k--','FDS 3 cm', ...
               'Sandia_He_1m_dx1p5cm_devc.csv','k-','FDS 1.5 cm')
           
radial_profile('Sandia_Plumes/Sandia_He_1m_YHe6','row',[170:190],0.5,'relative',10, ...
               'Radial Position (m)','Helium Mass Fraction','Sandia Helium Plume','$z = 0.6$ m','Northeast', ...
               -.5,.5,.05,-.5,.5,.1,0,1,.2, ...
               'Sandia_He_1m_YHe_zp6.csv','ko','Exp', ...
               'Sandia_He_1m_dx3cm_devc.csv','k--','FDS 3 cm', ...
               'Sandia_He_1m_dx1p5cm_devc.csv','k-','FDS 1.5 cm')

           
           
           
           