PROGRAM TWOWAYCOUPLING_EMULATOR

IMPLICIT NONE

INTEGER, PARAMETER :: FB = SELECTED_REAL_KIND(6)

CHARACTER(256) CHID,QFILE,EXECUTABLE
CHARACTER(1) OP_SYS

INTEGER COUNTER,VAR
REAL, ALLOCATABLE, DIMENSION(:,:) :: VERTS,TFACES,NEWVERTS
INTEGER, ALLOCATABLE, DIMENSION(:) :: SURF_IDS,MATL_IDS
INTEGER, ALLOCATABLE, DIMENSION(:,:) :: FACES,VOLUS

REAL(FB) TIME,TIMEGEOM
INTEGER OWNER_INDEX,I
INTEGER ONE_INTEGER,VERSION,N_FLOATS,N_INTS,FIRST_FRAME_STATIC,N_FACES,N_VERTS,N_VOLUS
INTEGER :: ONE=1

COUNTER=10

!WRITE(6,*) ' Enter Job ID string (CHID):'
!READ(*,'(a)') CHID
CHID='tetra_1'
CALL GETARG(1,EXECUTABLE)
CALL GETARG(2,OP_SYS)
IF (OP_SYS=='W') THEN
  CALL SYSTEMQQ ('start /b '//TRIM(EXECUTABLE)//' '//TRIM(CHID)//'.fds')
ELSE
  CALL SYSTEMQQ (TRIM(EXECUTABLE)//' '//TRIM(CHID)//'.fds &')
ENDIF

OPEN(10,FILE=TRIM(CHID)//'.gc',ACTION='WRITE',FORM='UNFORMATTED')
OWNER_INDEX=0
WRITE(10) OWNER_INDEX
CLOSE(10) 

!VARIABLE_NUMBER: DO VAR=1,VARIABLE
VAR=1
! 500 - Point of the loop in case of the point does not reach a meaning value - SILVA, JC         
500 CONTINUE

TIME_LOOP: DO TIMEGEOM=2,10,2

! wait for FDS flag
BOUNDARY_CHECK_LOOP: DO I=1,600
   OPEN(10,FILE=TRIM(CHID)//'.gc',ACTION='READ',FORM='UNFORMATTED')
   READ(10) OWNER_INDEX
   IF (OWNER_INDEX/=2) THEN
      CLOSE(10)
      IF (I==1) THEN
         WRITE (6,'(4X,A)')  'waiting for FDS results ... '
      ELSE 
         !WRITE(6,'(4X,A,I2,A)')  'waiting ... ', I-1,' min'
      ENDIF
      CALL SLEEP(15)
      IF (I==600) THEN
         WRITE (6,*) 'ERROR: .be FILE WAS NOT UPDATED BY FDS'
         STOP
      ENDIF
   ELSEIF (OWNER_INDEX==2) THEN
      CLOSE(10)
      EXIT BOUNDARY_CHECK_LOOP
   ENDIF
ENDDO BOUNDARY_CHECK_LOOP

QFILE='tetra_1_01.ge'
OPEN(12+VAR,FILE=QFILE,FORM='UNFORMATTED',STATUS='OLD')
READ(12+VAR) ONE_INTEGER
!WRITE(6,*) ONE_INTEGER
READ(12+VAR) VERSION
!WRITE(6,*) VERSION

!WRITE(12+VAR) ZERO, ZERO, ONE 

READ(12+VAR) N_FLOATS, N_INTS, FIRST_FRAME_STATIC
!WRITE(6,*) N_FLOATS, N_INTS, FIRST_FRAME_STATIC
READ(12+VAR) TIME
!WRITE(6,*) TIME 
READ(12+VAR) N_VERTS, N_FACES, N_VOLUS 
!WRITE(6,*) N_VERTS, N_FACES, N_VOLUS

!OPEN(16,FILE='verts.dat',FORM='FORMATTED',STATUS='UNKNOWN')

IF (N_VERTS>0) THEN
  ALLOCATE (VERTS(3,N_VERTS))            
  ALLOCATE (NEWVERTS(3,N_VERTS))     
  READ(12+VAR) VERTS
!  WRITE(6,*) VERTS
!  DO I=1,N_VERTS
!    WRITE(16,'(F8.5,F8.5,F8.5)') VERTS(1,I),VERTS(2,I),VERTS(3,I)
!  ENDDO
ENDIF

IF (N_FACES>0) THEN
   ALLOCATE (FACES(N_FACES,3))
   ALLOCATE (SURF_IDS(N_FACES))
   ALLOCATE (TFACES(N_FACES,6))
   READ(12+VAR) FACES
!   WRITE(6,*) FACES
   READ(12+VAR) SURF_IDS
!   WRITE(6,*) SURF_IDS
   READ(12+VAR) TFACES
ENDIF
IF (N_VOLUS>0) THEN
   ALLOCATE (VOLUS(N_VOLUS,4))
   ALLOCATE (MATL_IDS(N_VOLUS))
   READ(12+VAR) VOLUS
!   WRITE(6,*) VOLUS
   READ(12+VAR) MATL_IDS
!   WRITE(6,*) MATL_IDS
ENDIF

CLOSE(12+VAR) 

OPEN(12+VAR,FILE=TRIM(CHID)//'.gc',FORM='UNFORMATTED',STATUS='REPLACE')
WRITE(12+VAR) ONE
!WRITE(6,*) ONE
WRITE(12+VAR) VERSION
!WRITE(6,*) VERSION
!WRITE(12+VAR) ZERO,ZERO,ZERO
!WRITE(6,*) ZERO,ZERO,ZERO
!WRITE(12+VAR) TIME
!WRITE(6,*) TIME
!WRITE(12+VAR) N_VERTS, N_FACES, N_VOLUS 
!WRITE(6,*) N_VERTS, N_FACES, N_VOLUS 
!IF (N_VERTS>0) WRITE(12+VAR) VERTS
!IF (N_FACES>0) THEN
!  WRITE(12+VAR) FACES
!  WRITE(12+VAR) SURF_IDS
!  WRITE(12+VAR) TFACES
!ENDIF
!IF (N_VOLUS>0) THEN
!  WRITE(12+VAR) VOLUS
!  WRITE(12+VAR) MATL_IDS
!ENDIF

!ALLOCATE (DISP(3,N_VERTS))  
!ALLOCATE (NODE(N_VERTS))
!OPEN(15,FILE='displacements.dat',FORM='FORMATTED',STATUS='OLD')
!READ(15,'(I8)') N_STEPS


!DO J=1,N_STEPS 
!READ(15,'(F8.3)') TIME
!WRITE(6,*) TIME
!  DO I=1,N_VERTS
!    READ(15,'(I8)', ADVANCE='NO') NODE(I)
!    WRITE(6,*) NODE(I)
!    READ(15,'(F8.5,F8.5,F8.5)') DISP(1,I),DISP(2,I),DISP(3,I)
!    WRITE(6,*) DISP(1,I),DISP(2,I),DISP(3,I)
!  ENDDO

!DO I=1,N_VERTS
!  NEWVERTS(1,I)=VERTS(1,I)+DISP(1,I)
!  NEWVERTS(2,I)=VERTS(2,I)+DISP(2,I)
!  NEWVERTS(3,I)=VERTS(3,I)+DISP(3,I)
!ENDDO   
!WRITE(6,*) NEWVERTS
NEWVERTS=VERTS
NEWVERTS(3,4)=VERTS(3,4)-(0.1*(TIMEGEOM/2))

WRITE(12+VAR) TIMEGEOM
WRITE(12+VAR) N_VERTS, N_FACES, N_VOLUS 
!WRITE(6,*) N_VERTS, N_FACES, N_VOLUS 
IF (N_VERTS>0) WRITE(12+VAR) NEWVERTS
IF (N_FACES>0) THEN
  WRITE(12+VAR) FACES
  WRITE(12+VAR) SURF_IDS
  WRITE(12+VAR) TFACES
ENDIF
IF (N_VOLUS>0) THEN
  WRITE(12+VAR) VOLUS
  WRITE(12+VAR) MATL_IDS
ENDIF

!ENDDO

!LOOP_FDS2AST: DO I=1,COUNTER
!    WRITE (OUTFILE,'(g8.0)') INT(NOMASTER(I,1))
!    PRINT *, OUTFILE
!****************

!OPEN(100+VAR,FILE=TRIM(OUTFILE)//'.dat',FORM='FORMATTED',STATUS='UNKNOWN')
!      DO J=1,SIZE+1
!        WRITE (100+VAR,'(E12.5)', ADVANCE='NO') V_TIME(J)
!        WRITE (100+VAR,'(E12.5)', ADVANCE='YES') M_AST(I,J)
!      ENDDO
!    CLOSE (100+VAR)
!100 CONTINUE

!ENDDO LOOP_FDS2AST

!ENDDO IN_LOOP



!ENDDO VARIABLE_NUMBER
CLOSE(12+VAR)
!DEALLOCATE (DISP)  
!DEALLOCATE (NODE)
IF (N_VERTS>0) THEN
  DEALLOCATE (VERTS)            
  DEALLOCATE (NEWVERTS)
ENDIF
IF (N_FACES>0) THEN
  DEALLOCATE (FACES)
  DEALLOCATE (SURF_IDS)
  DEALLOCATE (TFACES)
ENDIF
IF (N_VOLUS>0) THEN
  DEALLOCATE (VOLUS)
  DEALLOCATE (MATL_IDS)
ENDIF
ENDDO TIME_LOOP

END PROGRAM TWOWAYCOUPLING_EMULATOR

