#!/bin/bash

$QFDS -d Immersed_Boundary_Method geom_arch.fds
$QFDS -d Immersed_Boundary_Method geom_azim.fds
$QFDS -d Immersed_Boundary_Method geom_elev.fds
$QFDS -d Immersed_Boundary_Method geom_obst.fds
$QFDS -d Immersed_Boundary_Method geom_scale.fds
$QFDS -d Immersed_Boundary_Method geom_simple.fds
#$QFDS -d Immersed_Boundary_Method geom_simple2.fds
$QFDS -d Immersed_Boundary_Method geom_slice.fds
$QFDS -d Immersed_Boundary_Method geom_sphere1a.fds
$QFDS -d Immersed_Boundary_Method geom_sphere1b.fds
$QFDS -d Immersed_Boundary_Method geom_sphere1c.fds
$QFDS -d Immersed_Boundary_Method geom_sphere1d.fds
$QFDS -d Immersed_Boundary_Method geom_sphere1e.fds
$QFDS -d Immersed_Boundary_Method geom_sphere1f.fds
$QFDS -d Immersed_Boundary_Method geom_sphere2.fds
#$QFDS -d Immersed_Boundary_Method geom_sphere2_fire.fds
$QFDS -d Immersed_Boundary_Method geom_sphere3a.fds
$QFDS -d Immersed_Boundary_Method geom_sphere3b.fds
$QFDS -d Immersed_Boundary_Method geom_sphere3c.fds
$QFDS -d Immersed_Boundary_Method geom_sphere3d.fds
$QFDS -d Immersed_Boundary_Method geom_sphere3e.fds
$QFDS -d Immersed_Boundary_Method geom_sphere3f.fds
$QFDS -d Immersed_Boundary_Method geom_sphere_fire.fds
$QFDS -d Immersed_Boundary_Method geom_terrain.fds
$QFDS -d Immersed_Boundary_Method geom_texture.fds
$QFDS -d Immersed_Boundary_Method geom_texture2.fds
$QFDS -d Immersed_Boundary_Method geom_texture3a.fds
$QFDS -d Immersed_Boundary_Method geom_texture3b.fds
$QFDS -d Immersed_Boundary_Method geom_texture4a.fds
$QFDS -d Immersed_Boundary_Method geom_texture4b.fds
$QFDS -d Immersed_Boundary_Method geom_time.fds
$QFDS -d Immersed_Boundary_Method geom_time2.fds
$QFDS -d Immersed_Boundary_Method geom_time3.fds
$QFDS -d Immersed_Boundary_Method geom_time4.fds
$QFDS -d Immersed_Boundary_Method geom_volume.fds
