#!/bin/bash

$QFDS -d CC_IBM geom_arch.fds
$QFDS -d CC_IBM geom_azim.fds
$QFDS -d CC_IBM geom_elev.fds
$QFDS -d CC_IBM geom_obst.fds
$QFDS -d CC_IBM geom_scale.fds
$QFDS -d CC_IBM geom_simple.fds
#$QFDS -d CC_IBM geom_simple2.fds
$QFDS -d CC_IBM geom_sphere1a.fds
$QFDS -d CC_IBM geom_sphere1b.fds
$QFDS -d CC_IBM geom_sphere1c.fds
$QFDS -d CC_IBM geom_sphere1d.fds
$QFDS -d CC_IBM geom_sphere1e.fds
$QFDS -d CC_IBM geom_sphere1f.fds
$QFDS -d CC_IBM geom_sphere2.fds
$QFDS -d CC_IBM geom_sphere2_fire.fds
$QFDS -d CC_IBM geom_sphere3a.fds
$QFDS -d CC_IBM geom_sphere3b.fds
$QFDS -d CC_IBM geom_sphere3c.fds
$QFDS -d CC_IBM geom_sphere3d.fds
$QFDS -d CC_IBM geom_sphere3e.fds
$QFDS -d CC_IBM geom_sphere3f.fds
$QFDS -d CC_IBM geom_sphere_fire.fds
$QFDS -d CC_IBM geom_terrain.fds
$QFDS -d CC_IBM geom_texture.fds
$QFDS -d CC_IBM geom_texture2.fds
$QFDS -d CC_IBM geom_texture3a.fds
$QFDS -d CC_IBM geom_texture3b.fds
$QFDS -d CC_IBM geom_texture4a.fds
$QFDS -d CC_IBM geom_texture4b.fds
$QFDS -d CC_IBM geom_time.fds
$QFDS -d CC_IBM geom_time2.fds
$QFDS -d CC_IBM geom_time3.fds
$QFDS -d CC_IBM geom_time4.fds
$QFDS -d CC_IBM geom_volume.fds
