#!/bin/sh
#PBS -N test_mpi_openmp
#PBS -o test_mpi_openmp.stdout
#PBS -e test_mpi_openmp.stderr
#PBS -q batch
#PBS -l nodes=3:ppn=8

echo Working directory is $PBS_O_WORKDIR
cd $PBS_O_WORKDIR
echo This jobs runs on the following nodes:
NODES=`cat $PBS_NODEFILE`
echo $NODES
NPROCS=`wc -l < $PBS_NODEFILE`
echo This job has allocated $NPROCS cores

export OMP_NUM_THREADS=4

mpirun --map-by ppr:2:node -np 6 ./test_mpi_openmp

