%	MATLAB PROGRAM
%	Title:			plotspec.m
%	Author:			Randy McDermott
%	Date:				4/22/2001
%
%	Description:	This program reads the file 'spec000.dat' which is
%						generated by Banff

close all
clear all

M1 = load('spec000.dat');
M2 = load('spec029.dat');
M3 = load('spec067.dat');

k = M1(:,1); %+ 100*0.1111/2.0; % Note: need to add this when using SdBK data

sf = 1;

tke000 = sf*M1(:,2);
tke028 = sf*M2(:,2);
tke066 = sf*M3(:,2);

%	Gather the Comte-Bellot/Corrsin data for comparison
%	Open and read the grid information
infile = fopen('cbcdata.txt','r');

%	Initialize the field
kCBC = zeros(20,1);
ECBC42 = zeros(20,1);
ECBC98 = zeros(20,1);
ECBC171 = zeros(20,1);

%	Read the data
for j = 1:20   
   kCBC(j) = fscanf(infile,'%f',1)*1e2;
   ECBC42(j) = fscanf(infile,'%f',1)/1e6;
   ECBC98(j) = fscanf(infile,'%f',1)/1e6;
   ECBC171(j) = fscanf(infile,'%f',1)/1e6;
end

%	Close the CBC dat file
fclose(infile);


%	Plot the FDS data
figure
H(1)=loglog(k(2:length(k)),tke000(2:length(k)),'k.-','MarkerSize',15);
hold on
H(2)=loglog(k(2:length(k)),tke028(2:length(k)),'r.-','MarkerSize',15);
H(2)=loglog(k(2:length(k)),tke066(2:length(k)),'b.-','MarkerSize',15);

%axis([xmin,xmax,ymin,ymax])
axis([10 1000 1/1e6 1000/1e6])
ylabel('E(k), m^3/s^2')
xlabel('k, 1/m')

%	Plot the CBC data
loglog(kCBC,ECBC42,'k-');
loglog(kCBC,ECBC98,'k-');
loglog(kCBC,ECBC171,'k-');

% Apply transfer function
N = 32;
k = kCBC;
k0 = 2*pi/(9*2*pi/100);
kmax = 1/2*N*k0;
delta = pi/kmax;
for j = 1:length(k)
    if k(j) <= kmax + 2*k0
        %G(j) = sin(1/2*k(j)*delta)/(1/2*k(j)*delta); % box filter
        G(j) = 1;
        %G(j) = exp(-k(j)^2*delta^2/24);
    else
        G(j) = 0;
    end
    E42(j)  = G(j)*G(j)*ECBC42(j);
    E98(j)  = G(j)*G(j)*ECBC98(j);
    E171(j) = G(j)*G(j)*ECBC171(j);
end

% % Plot the CBC data
% loglog(kCBC,E42,'g:')
% loglog(kCBC,E98,'b:')
% loglog(kCBC,E171,'r:')

% Add lines to indicate cutoff wavenumbers
loglog( [k0*N/2,k0*N/2],[1e-10,1e-2],'k--');     % LES Nyquist limit
%loglog([k0*N/2/2,k0*N/2/2],[1e-10,1e-2],'k-.');


    
