FORMULA,NAME
H2,HYDROGEN
H,HYDROGEN ATOM
O,OXYGEN ATOM
O2,OXYGEN
OH,HYDROXYL RADICAL
H2O,WATER VAPOR
HO2,HYDROPEROXY RADICAL
H2O2,HYDROGEN PEROXIDE
C,SOOT
CH,METHYLIDYNE
CH2,METHYLENE
CH2(S),METHYLENEs
CH3,METHYL RADICAL
CH4,METHANE
CO,CARBON MONOXIDE
CO2,CARBON DIOXIDE
HCO,FORMYL RADICAL
CH2O,FORMALDEHYDE
CH2OH,HYDROXYMETHYL RADICAL
CH2CHO,VINYLOXY RADICAL
CH3O,METHOXY RADICAL
CH3OH,METHANOL
C2H,ETHYNYL RADICAL
C2H2,ACETYLENE
C2H3,VINYL RADICAL
C2H4,ETHYLENE
C2H5,ETHYL RADICAL
C2H6,ETHANE
HCCO,KETENYL RADICAL
CH2CO,KETENE
HCCOH,ETHYNOL
N,NITROGEN ATOM
NH,IMIDOGEN
NNH,NNH
NH2,DINITROGEN MONOHYDRIDE
NH3,AMMONIA
NO,NITRIC OXIDE
NO2,NITROGEN DIOXIDE
N2O,NITROUS OXIDE
HNO,NITROSYL HYDRIDE
CN,CYANO RADICAL
HCN,HYDROGEN CYANIDE
H2CN,METHYLENE-AMIDOGEN
HCNN,HCNN
HCNO,FULMINIC ACID
HOCN,CYANIC ACID
HNCO,ISOCYANIC ACID
NCO,ISOCYANATO RADICAL
N2,NITROGEN
AR,ARGON
C3H7,ISOPROPYL RADICAL
C3H8,PROPANE
CH3CHO,ETHANAL