FORMULA,NAME,RADCAL_ID
H2,HYDROGEN,NONE
H,HYDROGEN ATOM,NONE
O,OXYGEN ATOM,NONE
O2,OXYGEN,NONE
OH,HYDROXYL RADICAL,NONE
H2O,WATER VAPOR,WATER VAPOR
HO2,HYDROPEROXY RADICAL,NONE
H2O2,HYDROGEN PEROXIDE,NONE
C,SOOTg,SOOT
CH,METHYLIDYNE,NONE
CH2,METHYLENE,NONE
CH2(S),METHYLENEs,NONE
CH3,METHYL RADICAL,METHANE
CH4,METHANE,METHANE
CO,CARBON MONOXIDE,CARBON DIOXIDE
CO2,CARBON DIOXIDE,CARBON MONOXIDE
HCO,FORMYL RADICAL,NONE
CH2O,FORMALDEHYDE,NONE
CH2OH,HYDROXYMETHYL RADICAL,NONE
CH2CHO,VINYLOXY RADICAL,NONE
CH3O,METHOXY RADICAL,METHANOL
CH3OH,METHANOL,METHANOL
C2H,ETHYNYL RADICAL,NONE
C2H2,ACETYLENE,ETHYLENE
C2H3,VINYL RADICAL,ETHYLENE
C2H4,ETHYLENE,ETHYLENE
C2H5,ETHYL RADICAL,NONE
C2H6,ETHANE,ETHANE
HCCO,KETENYL RADICAL,NONE
CH2CO,KETENE,NONE
HCCOH,ETHYNOL,NONE
N,NITROGEN ATOM,NONE
NH,IMIDOGEN,NONE
NNH,NNH,NONE
NH2,DINITROGEN MONOHYDRIDE,NONE
NH3,AMMONIA,NONE
NO,NITRIC OXIDE,NONE
NO2,NITROGEN DIOXIDE,NONE
N2O,NITROUS OXIDE,NONE
HNO,NITROSYL HYDRIDE,NONE
CN,CYANO RADICAL,NONE
HCN,HYDROGEN CYANIDE,NONE
H2CN,METHYLENE-AMIDOGEN,NONE
HCNN,HCNN,NONE
HCNO,FULMINIC ACID,NONE
HOCN,CYANIC ACID,NONE
HNCO,ISOCYANIC ACID,NONE
NCO,ISOCYANATO RADICAL,NONE
N2,NITROGEN,NONE
AR,ARGON,NONE
C3H7,ISOPROPYL RADICAL,PROPANE
C3H8,PROPANE,PROPANE
CH3CHO,ETHANAL,METHANOL