MODULE SOOT
 
! Compute soot deposition 
 
USE PRECISION_PARAMETERS
USE MESH_POINTERS

IMPLICIT NONE
PRIVATE
CHARACTER(255), PARAMETER :: sootid='$Id: soot.f90 3318 2009-02-15 20:00:26Z mcgratta $'
CHARACTER(255), PARAMETER :: sootrev='$Revision: 3318 $'
CHARACTER(255), PARAMETER :: sootdate='$Date: 2009-02-15 15:00:26 -0500 (Sun, 15 Feb 2009) $'

PUBLIC CALC_SOOT_DEPOSITION
 
 
CONTAINS
 
SUBROUTINE CALC_SOOT_DEPOSITION(NM)
USE PHYSICAL_FUNCTIONS, ONLY: GET_VISCOSITY
USE GLOBAL_CONSTANTS, ONLY: EVACUATION_ONLY,SOLID_PHASE_ONLY,SOLID_BOUNDARY,I_PROG_SOOT,N_SPECIES,TUSED
USE COMP_FUNCTIONS, ONLY:SECOND
INTEGER, INTENT(IN) :: NM
REAL(EB), PARAMETER :: CS=1.147_EB,CT=2.18_EB,CM=1.146_EB,KPKG=1._EB,PARTD=2.E-8_EB
REAL(EB) :: U1,U_THERM,U_TURB,TGAS,TWALL,MFP,MUGAS,KN,CC,Y_SOOT,RHOG,TNOW,YIN(1:N_SPECIES),YDEP,NU_OVER_DZ
INTEGER  :: II,JJ,KK,IIG,JJG,KKG,IW,IOR,ITMP

REAL(EB), PARAMETER :: A=8.3_EB,B=1._EB/7._EB,Z_PLUS_TURBULENT = 11.81_EB,ALPHA=7.202125273562269_EB 
REAL(EB), PARAMETER :: BETA=1._EB+B,ETA=(1._EB+B)/A,GAMMA=2._EB/(1._EB+B)

 
IF (EVACUATION_ONLY(NM)) RETURN
IF (SOLID_PHASE_ONLY) RETURN

TNOW=SECOND()
CALL POINT_TO_MESH(NM)
 
WALL_CELL_LOOP: DO IW=1,NWC+NVWC
   IF (BOUNDARY_TYPE(IW)/=SOLID_BOUNDARY .OR. UW(IW) < 0._EB) CYCLE WALL_CELL_LOOP
   II  = IJKW(1,IW)
   JJ  = IJKW(2,IW)
   KK  = IJKW(3,IW)
   IOR = IJKW(4,IW)
   IIG = IJKW(6,IW)
   JJG = IJKW(7,IW)
   KKG = IJKW(8,IW)
   YIN = YY(IIG,JJG,KKG,:)
   Y_SOOT = YIN(I_PROG_SOOT)
   IF (Y_SOOT < 1.E-14_EB) CYCLE WALL_CELL_LOOP
   TGAS = TMP(IIG,JJG,KKG)
   TWALL = TMP_W(IW)
   SELECT CASE(ABS(IOR))
      CASE(1)
         U1 = SQRT(0.25_EB*(V(IIG,JJG-1,KKG)+V(IIG,JJG,KKG))**2+0.25_EB*(W(IIG,JJG,KKG-1)+W(IIG,JJG,KKG))**2)
      CASE(2)
         U1 = SQRT(0.25_EB*(U(IIG-1,JJG,KKG)+U(IIG,JJG,KKG))**2+0.25_EB*(W(IIG,JJG,KKG-1)+W(IIG,JJG,KKG))**2)
      CASE(3)
         U1 = SQRT(0.25_EB*(U(IIG-1,JJG,KKG)+U(IIG,JJG,KKG))**2+0.25_EB*(V(IIG,JJG-1,KKG)+V(IIG,JJG,KKG))**2)
   END SELECT   
   ITMP = MIN(NINT(TGAS),5000)
   CALL GET_VISCOSITY(YIN,MUGAS,ITMP)
   RHOG=RHO(IIG,JJG,KKG)
   NU_OVER_DZ=MUGAS/RHOG*RDN(IW)
   !MFP = MUGAS * SQRT(PI/(2._EB*PBAR(KKG,PRESSURE_ZONE(IIG,JJG,KKG))*RHOG))
   !KN = 2._EB*MFP/PARTD
   !CC = 1+ KN * (1.257_EB+0.4_EB*EXP(-1.1/KN))
   !U_THERM = 2._EB *CC*CS*(KPKG+CT*KN)*(TGAS-TWALL)*RDN(IW)/TGAS*MUGAS/RHOG/((1._EB+3._EB*CM*KN)*(1._EB+2._EB*KPKG+2._EB*CT*KN))
   U_THERM = 0.55_EB*(TGAS-TWALL)*RDN(IW)/TGAS*MUGAS/RHOG
   U_TURB = 0.175_EB*SQRT((ALPHA*NU_OVER_DZ**BETA + ETA*NU_OVER_DZ**B*ABS(U1))**GAMMA) 
   IF (U_THERM+U_TURB < 0._EB) CYCLE WALL_CELL_LOOP
   YDEP =Y_SOOT*MIN(1._EB,(U_THERM+U_TURB)*DT*RDN(IW))
   YY(IIG,JJG,KKG,I_PROG_SOOT) = Y_SOOT - YDEP
   YY(IIG,JJG,KKG,:) = YY(IIG,JJG,KKG,:)/(1._EB-YDEP)
   AWMSOOT(IW)=AWMSOOT(IW)+YDEP*RHOG/RDN(IW)
   RHO(IIG,JJG,KKG) = (1._EB-YDEP)*RHOG

ENDDO WALL_CELL_LOOP

TUSED(10,NM)=TUSED(10,NM)+SECOND()-TNOW

END SUBROUTINE CALC_SOOT_DEPOSITION


!---------------------------------------------------------------------------

SUBROUTINE GET_REV_soot(MODULE_REV,MODULE_DATE)
INTEGER,INTENT(INOUT) :: MODULE_REV
CHARACTER(255),INTENT(INOUT) :: MODULE_DATE
WRITE(MODULE_DATE,'(A)') sootrev(INDEX(sootrev,':')+1:LEN_TRIM(sootrev)-2)
READ (MODULE_DATE,'(I5)') MODULE_REV
WRITE(MODULE_DATE,'(A)') sootdate
END SUBROUTINE GET_REV_soot
 
END MODULE SOOT
