@echo off
..\intel_win_64\geomtest test_azim.fds
..\intel_win_64\geomtest test_component.fds
..\intel_win_64\geomtest test_elev.fds
..\intel_win_64\geomtest test_group.fds
..\intel_win_64\geomtest test_group2.fds
..\intel_win_64\geomtest test_group3.fds
..\intel_win_64\geomtest test_scale.fds
..\intel_win_64\geomtest test_time.fds
..\intel_win_64\geomtest test_time2.fds
..\intel_win_64\geomtest test_time3.fds
..\intel_win_64\geomtest test_time4.fds
..\intel_win_64\geomtest test_time5.fds
