PROGRAM TWOWAYCOUPLING_EMULATOR

IMPLICIT NONE

INTEGER, PARAMETER :: FB = SELECTED_REAL_KIND(6)
INTEGER :: IERR, NMESHES, NM, I, J
INTEGER :: IFILE, NSAM
!INTEGER :: I1, I2, J1, J2, K1, K2, I3, J3, K3
!INTEGER :: NPATCH, IJBAR, JKBAR,II

TYPE MESH_TYPE
   REAL(FB), POINTER, DIMENSION(:) :: X,Y,Z
   REAL(FB) :: D1,D2,D3,D4
   INTEGER :: IBAR,JBAR,KBAR,IERR
END TYPE MESH_TYPE
 
TYPE (MESH_TYPE), DIMENSION(:), ALLOCATABLE, TARGET :: MESH
TYPE (MESH_TYPE), POINTER :: M
 
!INTEGER, ALLOCATABLE, DIMENSION(:) :: IOR,I1B,I2B,J1B,J2B,K1B,K2B
!REAL(FB), ALLOCATABLE, DIMENSION(:,:,:,:) :: Q
!REAL(FB), ALLOCATABLE, DIMENSION(:,:,:) :: F
!LOGICAL, ALLOCATABLE, DIMENSION(:,:,:) :: ALREADY_USED
CHARACTER(2) :: ANS
CHARACTER(4) :: CHOICE
CHARACTER(256) GRIDFILE,CHID,QFILE,JUNK,EXECUTABLE
CHARACTER(256), DIMENSION(500) :: BNDF_FILE,BNDF_TEXT,BNDF_UNIT
CHARACTER(20), DIMENSION(500) :: BNDF_TYPE
CHARACTER(20) :: BNDF_TYPE_CHOSEN
!REAL(FB), DIMENSION(500) :: X1, X2, Y1, Y2, Z1, Z2
!INTEGER,  DIMENSION(60) :: IB
INTEGER,  DIMENSION(500) :: BNDF_MESH
INTEGER :: RCODE
INTEGER :: NFILES_EXIST
LOGICAL :: EXISTS
INTEGER :: BATCHMODE
!CHARACTER(256) :: BUFFER
!INTEGER :: ERROR_STATUS
!CHARACTER(256) :: ARG

INTEGER COUNTER,VAR
INTEGER SIZE,VARIABLE,IN
REAL TBEG,TEND,TINT
REAL NOMASTER(1,4)
REAL, ALLOCATABLE, DIMENSION(:,:) :: VERTS,TFACES,DISP,NEWVERTS
INTEGER, ALLOCATABLE, DIMENSION(:) :: SURF_IDS,MATL_IDS,NODE
INTEGER, ALLOCATABLE, DIMENSION(:,:) :: FACES,VOLUS
CHARACTER(8) OUTFILE

REAL(FB) TIME,TIMEGEOM
INTEGER N_FACE(4),OWNER_INDEX
INTEGER ONE_INTEGER,VERSION,N_FLOATS,N_INTS,FIRST_FRAME_STATIC,N_FACES,N_VERTS,N_VOLUS,N_STEPS
INTEGER :: ONE=1, ZERO=0

WRITE(6,*) 'COUPLING EMULATOR running tetra_1 case'

!WRITE(6,*) ' Enter Job ID string (CHID):'
!READ(*,'(a)') CHID
CHID='tetra_1'
CALL GETARG(1,EXECUTABLE)

#ifdef pp_WINDOWS
CALL SYSTEMQQ ('start /b '//TRIM(EXECUTABLE)//' '//TRIM(CHID)//'.fds &')
#else
CALL SYSTEMQQ (TRIM(EXECUTABLE)//' '//TRIM(CHID)//'.fds &')
#endif

OPEN(10,FILE=TRIM(CHID)//'.gc',ACTION='WRITE',FORM='UNFORMATTED')
OWNER_INDEX=0
WRITE(10) OWNER_INDEX
CLOSE(10)  

! Set a few default values
BATCHMODE=0

TIME_LOOP: DO TIMEGEOM=2,10,2

! wait for FDS flag
BOUNDARY_CHECK_LOOP: DO I=1,600
   OPEN(10,FILE=TRIM(CHID)//'.gc',ACTION='READ',FORM='UNFORMATTED')
   READ(10) OWNER_INDEX
   IF (OWNER_INDEX/=2) THEN
      CLOSE(10)
      IF (I==1) THEN
         WRITE (6,'(4X,A)')  'COUPLING: waiting for FDS results ... '
      ELSE 
         !WRITE(6,'(4X,A,I2,A)')  'waiting ... ', I-1,' min'
      ENDIF
      CALL SLEEP(15)
      IF (I==600) THEN
         WRITE (6,*) 'ERROR: .be FILE WAS NOT UPDATED BY FDS'
         STOP
      ENDIF
   ELSEIF (OWNER_INDEX==2) THEN
      CLOSE(10)
      EXIT BOUNDARY_CHECK_LOOP
   ENDIF
ENDDO BOUNDARY_CHECK_LOOP


OPEN(12,FILE=TRIM(CHID)//'_01.ge',FORM='UNFORMATTED',STATUS='OLD', IOSTAT=RCODE)
READ(12) ONE_INTEGER
READ(12) VERSION
READ(12) N_FLOATS, N_INTS, FIRST_FRAME_STATIC
READ(12) TIME
READ(12) N_VERTS, N_FACES, N_VOLUS 

IF (N_VERTS>0) THEN
  ALLOCATE (VERTS(3,N_VERTS))            
  ALLOCATE (NEWVERTS(3,N_VERTS))     
  READ(12) VERTS
ENDIF

IF (N_FACES>0) THEN
   ALLOCATE (FACES(N_FACES,3))
   ALLOCATE (SURF_IDS(N_FACES))
   ALLOCATE (TFACES(N_FACES,6))
   READ(12) FACES
   READ(12) SURF_IDS
   READ(12) TFACES
ENDIF
IF (N_VOLUS>0) THEN
   ALLOCATE (VOLUS(N_VOLUS,4))
   ALLOCATE (MATL_IDS(N_VOLUS))
   READ(12) VOLUS
   READ(12) MATL_IDS
ENDIF

CLOSE(12) 

OPEN(13,FILE=TRIM(CHID)//'.gc',FORM='UNFORMATTED',STATUS='REPLACE')
WRITE(13) ONE
WRITE(13) VERSION

ALLOCATE (DISP(3,N_VERTS))  
ALLOCATE (NODE(N_VERTS))
!OPEN(15,FILE='displacements.dat',FORM='FORMATTED',STATUS='OLD')
!READ(15,'(I8)') N_STEPS


!DO J=1,N_STEPS 
!READ(15,'(F8.3)') TIME
!WRITE(6,*) TIME
!  DO I=1,N_VERTS
!    READ(15,'(I8)', ADVANCE='NO') NODE(I)
!    WRITE(6,*) NODE(I)
!    READ(15,'(F8.5,F8.5,F8.5)') DISP(1,I),DISP(2,I),DISP(3,I)
!    WRITE(6,*) DISP(1,I),DISP(2,I),DISP(3,I)
!  ENDDO

!DO I=1,N_VERTS
!  NEWVERTS(1,I)=VERTS(1,I)+DISP(1,I)
!  NEWVERTS(2,I)=VERTS(2,I)+DISP(2,I)
!  NEWVERTS(3,I)=VERTS(3,I)+DISP(3,I)
!ENDDO   
!WRITE(6,*) NEWVERTS
NEWVERTS=VERTS
NEWVERTS(3,4)=VERTS(3,4)-(0.1*(TIMEGEOM/2))
WRITE(6,*) NEWVERTS

WRITE(13) TIMEGEOM
WRITE(13) N_VERTS, N_FACES, N_VOLUS 
!WRITE(6,*) N_VERTS, N_FACES, N_VOLUS 
IF (N_VERTS>0) WRITE(13) NEWVERTS
IF (N_FACES>0) THEN
  WRITE(13) FACES
  WRITE(13) SURF_IDS
  WRITE(13) TFACES
ENDIF
IF (N_VOLUS>0) THEN
  WRITE(13) VOLUS
  WRITE(13) MATL_IDS
ENDIF

CLOSE(13)
DEALLOCATE (DISP)  
DEALLOCATE (NODE)
DEALLOCATE (VERTS)            
DEALLOCATE (NEWVERTS)
DEALLOCATE (FACES)
DEALLOCATE (SURF_IDS)
DEALLOCATE (TFACES)
DEALLOCATE (VOLUS)
DEALLOCATE (MATL_IDS)
ENDDO TIME_LOOP

END PROGRAM TWOWAYCOUPLING_EMULATOR


