#!/bin/sh
#PBS -N test_mpi_openmp
#PBS -o test_mpi_openmp.stdout
#PBS -e test_mpi_openmp.stderr
#PBS -q batch
#PBS -l nodes=2:ppn=4
echo Working directory is $PBS_O_WORKDIR
cd $PBS_O_WORKDIR
echo This jobs runs on the following processors:
NODES=`cat $PBS_NODEFILE`
echo $NODES
NPROCS=`wc -l < $PBS_NODEFILE`
echo This job has allocated $NPROCS nodes

export OMP_NUM_THREADS=4

mpiexec --map-by node -np 2 ./test_mpi_openmp

