smokeview -update_ssf cell_test
smokeview -update_ssf cfast_test
smokeview -update_ssf colorbar
smokeview -update_ssf colorconv
smokeview -update_ssf fed_test
smokeview -update_ssf mplume5c8
smokeview -update_ssf objects_dynamic
smokeview -update_ssf objects_elem
smokeview -update_ssf objects_static
smokeview -update_ssf plume5c
smokeview -update_ssf plume5cdelta
smokeview -update_ssf plume5c_bounddef
smokeview -update_ssf plume5c_diff
smokeview -update_ssf plumeiso
smokeview -update_ssf script_slice_test
smokeview -update_ssf script_test
smokeview -update_ssf sillytexture
smokeview -update_ssf slicemask
smokeview -update_ssf smoke_sensor
smokeview -update_ssf smoke_test
smokeview -update_ssf smoke_test2
smokeview -update_ssf sprinkler_many
smokeview -update_ssf thouse5
smokeview -update_ssf thouse5delta
smokeview -update_ssf thouse5_diff
smokeview -update_ssf transparency
smokeview -update_ssf vcirctest
smokeview -update_ssf vcirctest2
smokeview -update_ssf version
