MODULE MESH_VARIABLES
 
! Data structure for mesh-dependent variables
 
USE PRECISION_PARAMETERS
USE TYPES
IMPLICIT NONE

CHARACTER(255), PARAMETER :: meshid='$Id$'
CHARACTER(255), PARAMETER :: meshrev='$Revision$'
CHARACTER(255), PARAMETER :: meshdate='$Date$'
 
TYPE MESH_TYPE
 
   REAL(EB), POINTER, DIMENSION(:,:,:) :: &
            U,V,W,US,VS,WS,DDDT,D,DS,H,HP,FVX,FVY,FVZ,RHO,RHOS, &
            MU,TMP,Q,FRHO,KAPPA,QR,QR_W,UII,RSUM,Z_SUM,Y_SUM,D_VAP
   REAL(EB), POINTER, DIMENSION(:,:,:,:) :: YY,YYS,DEL_RHO_D_DEL_Y,AVG_DROP_DEN,AVG_DROP_TMP,AVG_DROP_RAD
   REAL(EB), POINTER, DIMENSION(:,:) :: UVW_GHOST
 
   REAL(EB) :: POIS_PTB,POIS_ERR
   REAL(EB), POINTER, DIMENSION(:) :: SAVE,SAVE2,WORK
   REAL(EB), POINTER, DIMENSION(:,:,:) :: PRHS
   REAL(EB), POINTER, DIMENSION(:,:) :: BXS,BXF,BYS,BYF,BZS,BZF, BXST,BXFT,BYST,BYFT,BZST,BZFT
   INTEGER :: LSAVE,LWORK,LBC,MBC,NBC,ITRN,JTRN,KTRN,IPS
   REAL(EB), POINTER, DIMENSION(:) :: P_0,RHO_0,TMP_0,D_PBAR_DT,D_PBAR_S_DT,U_LEAK,U_DUCT
   REAL(EB), POINTER, DIMENSION(:,:) :: PBAR,PBAR_S,R_PBAR,LEAK_AREA,FDS_LEAK_AREA
   INTEGER, POINTER, DIMENSION(:,:,:) :: PRESSURE_ZONE 
   INTEGER, POINTER, DIMENSION(:) :: PRESSURE_ZONE_WALL
 
   REAL(EB), POINTER, DIMENSION(:,:,:) :: WORK1,WORK2,WORK3,WORK4,WORK5,WORK6,WORK7
   LOGICAL, POINTER, DIMENSION(:,:,:) :: LOGICAL_WORK
   REAL(EB), POINTER, DIMENSION(:) :: WALL_WORK1,WALL_WORK2
   REAL(FB), POINTER, DIMENSION(:,:,:,:) :: QQ
   REAL(FB), POINTER, DIMENSION(:,:) :: PP,PPN
   INTEGER, POINTER, DIMENSION(:,:) :: IBK
   INTEGER, POINTER, DIMENSION(:,:,:) :: IBLK
 
   REAL(EB) :: DT,DTOLD,DTNEXT,DTINT
   REAL(EB) :: CFL,DIVMX,DIVMN,VN,RESMAX
   INTEGER  :: ICFL,JCFL,KCFL,IMX,JMX,KMX,IMN,JMN,KMN, I_VN,J_VN,K_VN,IRM,JRM,KRM
 
   INTEGER :: N_EDGES
   INTEGER, POINTER, DIMENSION(:,:) :: IJKE,EDGE_INDEX
   REAL(EB), POINTER, DIMENSION(:) :: TAU_E,OME_E
   LOGICAL, POINTER, DIMENSION(:) :: ACTIVE_EDGE
 
   INTEGER :: IBAR,JBAR,KBAR,IBAR2,JBAR2,KBAR2,IBM1,JBM1,KBM1,IBP1,JBP1,KBP1
   INTEGER, POINTER, DIMENSION(:) :: I_LO,I_HI,J_LO,J_HI,K_LO,K_HI
   INTEGER, POINTER, DIMENSION(:,:,:) :: CGI,CGI2
   INTEGER, POINTER, DIMENSION(:) :: RGB
   REAL(EB) :: DXI,DETA,DZETA,RDXI,RDETA,RDZETA, &
      DXMIN,DXMAX,DYMIN,DYMAX,DZMIN,DZMAX, &
      XS,XF,YS,YF,ZS,ZF,RDXINT,RDYINT,RDZINT
   REAL(EB), POINTER, DIMENSION(:) :: R,RC,X,Y,Z,XC,YC,ZC,HX,HY,HZ, &
            DX,RDX,DXN,RDXN,DY,RDY,DYN,RDYN,DZ,RDZ,DZN,RDZN, &
            CELLSI,CELLSJ,CELLSK,RREDX,RREDY,RREDZ,RRN
   REAL(FB), POINTER, DIMENSION(:) :: XPLT,YPLT,ZPLT
 
   INTEGER :: N_OBST
   TYPE(OBSTRUCTION_TYPE), POINTER, DIMENSION(:) :: OBSTRUCTION
 
   INTEGER :: N_VENT
   TYPE(VENTS_TYPE), POINTER, DIMENSION(:) :: VENTS
 
   INTEGER, POINTER, DIMENSION(:,:,:) :: CELL_INDEX
   INTEGER, POINTER, DIMENSION(:) :: I_CELL,J_CELL,K_CELL,OBST_INDEX_C
   INTEGER, POINTER, DIMENSION(:,:) :: WALL_INDEX
   LOGICAL, POINTER, DIMENSION(:) :: SOLID
 
   INTEGER :: NWC,NEWC,NDWC,CELL_COUNT,WALL_COUNTER
   REAL(EB) :: BC_CLOCK
   REAL(EB), POINTER, DIMENSION(:,:) :: MASSFLUX,AWMPUA,WMPUA,WCPUA
   REAL(EB), POINTER, DIMENSION(:,:) :: RHODW,YY_W,INTERPOLATION_FACTOR
   REAL(EB), POINTER, DIMENSION(:)   :: XW,YW,ZW,TW, &
            AW,RAW,UW0,DUWDT,RDN,MASS_LOSS, &
            QRADIN,QRADOUT,EW,KW,QCONF,AREA_ADJUST,RHO_W,TMP_W,RSUM_W,RCP_W, &
            TMP_F,TMP_B,HEAT_TRANS_COEF
   REAL(EB), POINTER, DIMENSION(:) :: E_WALL,ACTUAL_BURN_RATE
   REAL(EB), POINTER, DIMENSION(:) :: UW,UWS,CELL_VOLUME_RATIO
   INTEGER, POINTER, DIMENSION(:,:) :: IJKW
   INTEGER, POINTER, DIMENSION(:) :: BOUNDARY_TYPE,NPPCW,OBST_INDEX_W,WALL_INDEX_BACK,VENT_INDEX
 
   TYPE(WALL_TYPE), POINTER, DIMENSION(:) :: WALL
   TYPE(OMESH_TYPE), POINTER, DIMENSION(:) :: OMESH
   TYPE(DROPLET_TYPE), POINTER, DIMENSION(:) :: DROPLET
   INTEGER :: NLP,NLPDIM
   TYPE(HUMAN_TYPE), POINTER, DIMENSION(:) :: HUMAN
   INTEGER :: N_HUMANS,N_HUMANS_DIM
   TYPE(HUMAN_GRID_TYPE), POINTER, DIMENSION(:,:) :: HUMAN_GRID
 
   INTEGER :: N_SLCF
   TYPE(SLICE_TYPE), POINTER, DIMENSION(:) :: SLICE
 
   INTEGER, POINTER, DIMENSION(:,:) :: INC
   INTEGER :: NPATCH
 
   REAL(EB), POINTER, DIMENSION(:,:,:,:) :: UIID
   INTEGER :: RAD_CALL_COUNTER,ANGLE_INC_COUNTER
 
   REAL(EB) :: RHO_AVG,Q_UPPER
 
   INTEGER, POINTER, DIMENSION(:,:,:) :: INTERPOLATED_MESH
 
   CHARACTER(80), POINTER, DIMENSION(:) :: STRING
   INTEGER :: N_STRINGS,N_STRINGS_MAX
 
END TYPE MESH_TYPE
 
TYPE (MESH_TYPE), SAVE, DIMENSION(:), ALLOCATABLE, TARGET :: MESHES
 
CHARACTER(30), DIMENSION(:), ALLOCATABLE :: MESH_NAME
REAL(EB),DIMENSION(:,:), ALLOCATABLE :: TUSED
INTEGER, DIMENSION(:,:), ALLOCATABLE ::  I_MIN,I_MAX,J_MIN,J_MAX,K_MIN,K_MAX,NIC
 
END MODULE MESH_VARIABLES
 
 
MODULE MESH_POINTERS
 
USE PRECISION_PARAMETERS
USE MESH_VARIABLES
IMPLICIT NONE
 
REAL(EB), POINTER, DIMENSION(:,:,:) :: &
          U,V,W,US,VS,WS,DDDT,D,DS,H,HP,FVX,FVY,FVZ,RHO,RHOS, &
          MU,TMP,Q,FRHO,KAPPA,QR,QR_W,UII,RSUM,Y_SUM,Z_SUM,D_VAP
REAL(EB), POINTER, DIMENSION(:,:,:,:) :: YY,YYS,DEL_RHO_D_DEL_Y,AVG_DROP_DEN,AVG_DROP_TMP,AVG_DROP_RAD 
REAL(EB), POINTER, DIMENSION(:,:) :: UVW_GHOST
REAL(EB), POINTER :: POIS_PTB,POIS_ERR
REAL(EB), POINTER, DIMENSION(:) :: SAVE,SAVE2,WORK
REAL(EB), POINTER, DIMENSION(:,:,:) :: PRHS
REAL(EB), POINTER, DIMENSION(:,:) :: BXS,BXF,BYS,BYF,BZS,BZF, BXST,BXFT,BYST,BYFT,BZST,BZFT
INTEGER, POINTER :: LSAVE,LWORK,LBC,MBC,NBC,ITRN,JTRN,KTRN,IPS
REAL(EB), POINTER, DIMENSION(:) :: P_0,RHO_0,TMP_0,D_PBAR_DT,D_PBAR_S_DT,U_LEAK,U_DUCT
REAL(EB), POINTER, DIMENSION(:,:) :: PBAR,PBAR_S,R_PBAR,LEAK_AREA,FDS_LEAK_AREA
INTEGER, POINTER, DIMENSION(:,:,:) :: PRESSURE_ZONE
INTEGER, POINTER, DIMENSION(:) :: PRESSURE_ZONE_WALL
REAL(EB), POINTER, DIMENSION(:,:,:) :: WORK1,WORK2,WORK3,WORK4,WORK5,WORK6,WORK7
LOGICAL, POINTER, DIMENSION(:,:,:) :: LOGICAL_WORK
REAL(EB), POINTER, DIMENSION(:) :: WALL_WORK1,WALL_WORK2
REAL(FB), POINTER, DIMENSION(:,:,:,:) :: QQ
REAL(FB), POINTER, DIMENSION(:,:) :: PP,PPN
INTEGER, POINTER, DIMENSION(:,:) :: IBK
INTEGER, POINTER, DIMENSION(:,:,:) :: IBLK
REAL(EB), POINTER :: DT,DTOLD,DTNEXT,DTINT
REAL(EB), POINTER :: CFL,DIVMX,DIVMN,VN,RESMAX
INTEGER, POINTER :: ICFL,JCFL,KCFL,IMX,JMX,KMX,IMN,JMN,KMN,I_VN,J_VN,K_VN,IRM,JRM,KRM
INTEGER, POINTER :: N_EDGES
INTEGER, POINTER, DIMENSION(:,:) :: IJKE,EDGE_INDEX
REAL(EB), POINTER, DIMENSION(:) :: TAU_E,OME_E
LOGICAL, POINTER, DIMENSION(:) :: ACTIVE_EDGE
INTEGER, POINTER :: IBAR,JBAR,KBAR,IBAR2,JBAR2,KBAR2,IBM1,JBM1,KBM1,IBP1,JBP1,KBP1
INTEGER, POINTER, DIMENSION(:) :: I_LO,I_HI,J_LO,J_HI,K_LO,K_HI
INTEGER, POINTER, DIMENSION(:,:,:) :: CGI,CGI2
INTEGER, POINTER, DIMENSION(:) :: RGB
REAL(EB), POINTER :: DXI,DETA,DZETA,RDXI,RDETA,RDZETA, &
   DXMIN,DXMAX,DYMIN,DYMAX,DZMIN,DZMAX, &
   XS,XF,YS,YF,ZS,ZF,RDXINT,RDYINT,RDZINT
REAL(EB), POINTER, DIMENSION(:) :: R,RC,X,Y,Z,XC,YC,ZC,HX,HY,HZ, &
           DX,RDX,DXN,RDXN,DY,RDY,DYN,RDYN,DZ,RDZ,DZN,RDZN, &
           CELLSI,CELLSJ,CELLSK,RREDX,RREDY,RREDZ,RRN
REAL(FB), POINTER, DIMENSION(:) :: XPLT,YPLT,ZPLT
INTEGER, POINTER :: N_OBST
TYPE(OBSTRUCTION_TYPE), POINTER, DIMENSION(:) :: OBSTRUCTION
INTEGER, POINTER :: N_VENT
TYPE(VENTS_TYPE), POINTER, DIMENSION(:) :: VENTS
INTEGER, POINTER, DIMENSION(:,:,:) :: CELL_INDEX
INTEGER, POINTER, DIMENSION(:) :: I_CELL,J_CELL,K_CELL,OBST_INDEX_C
INTEGER, POINTER, DIMENSION(:,:) :: WALL_INDEX
LOGICAL, POINTER, DIMENSION(:) :: SOLID
INTEGER, POINTER :: NWC,NEWC,NDWC,CELL_COUNT,WALL_COUNTER
REAL(EB),POINTER :: BC_CLOCK
REAL(EB), POINTER, DIMENSION(:,:) :: MASSFLUX,AWMPUA,WMPUA,WCPUA
REAL(EB), POINTER, DIMENSION(:,:) :: RHODW,YY_W,INTERPOLATION_FACTOR
REAL(EB), POINTER, DIMENSION(:)   :: XW,YW,ZW,TW, &
           AW,RAW,UW0,DUWDT,RDN,MASS_LOSS, &
           QRADIN,QRADOUT,EW,KW,QCONF,AREA_ADJUST,RHO_W,TMP_W,RSUM_W,RCP_W, &
           TMP_F,TMP_B,HEAT_TRANS_COEF
REAL(EB), POINTER, DIMENSION(:) :: E_WALL,ACTUAL_BURN_RATE
REAL(EB), POINTER, DIMENSION(:) :: UW,UWS,CELL_VOLUME_RATIO
INTEGER, POINTER, DIMENSION(:,:) :: IJKW
INTEGER, POINTER, DIMENSION(:) :: BOUNDARY_TYPE,NPPCW,OBST_INDEX_W,WALL_INDEX_BACK,VENT_INDEX
TYPE(WALL_TYPE), POINTER, DIMENSION(:) :: WALL
TYPE(OMESH_TYPE), POINTER, DIMENSION(:) :: OMESH
TYPE(DROPLET_TYPE), POINTER, DIMENSION(:) :: DROPLET
INTEGER, POINTER :: NLP,NLPDIM
TYPE(HUMAN_TYPE), POINTER, DIMENSION(:) :: HUMAN
INTEGER, POINTER :: N_HUMANS,N_HUMANS_DIM
TYPE(HUMAN_GRID_TYPE), POINTER, DIMENSION(:,:) :: HUMAN_GRID
INTEGER, POINTER :: N_SLCF
TYPE(SLICE_TYPE), POINTER, DIMENSION(:) :: SLICE
INTEGER, POINTER, DIMENSION(:,:) :: INC
INTEGER, POINTER :: NPATCH
REAL(EB), POINTER, DIMENSION(:,:,:,:) :: UIID
INTEGER,  POINTER :: RAD_CALL_COUNTER,ANGLE_INC_COUNTER
REAL(EB), POINTER :: RHO_AVG,Q_UPPER
INTEGER, POINTER, DIMENSION(:,:,:) :: INTERPOLATED_MESH
CHARACTER(80), POINTER, DIMENSION(:) :: STRING
INTEGER, POINTER :: N_STRINGS,N_STRINGS_MAX

CONTAINS
 
 
SUBROUTINE POINT_TO_MESH(NM)

! Local names for MESH variables point to Global names
 
INTEGER, INTENT(IN) ::  NM
TYPE (MESH_TYPE), POINTER :: M
 
M=>MESHES(NM)
U=>M%U
V=>M%V
W=>M%W
US=>M%US
VS=>M%VS
WS=>M%WS
DDDT=>M%DDDT
D=>M%D
DS=>M%DS
H=>M%H 
HP=>M%HP
FVX=>M%FVX
FVY=>M%FVY
FVZ=>M%FVZ  
RHO=>M%RHO
RHOS=>M%RHOS
TMP=>M%TMP
FRHO=>M%FRHO
MU=>M%MU
Q=>M%Q
QR=>M%QR
QR_W=>M%QR_W
KAPPA=>M%KAPPA 
UII=>M%UII 
AVG_DROP_DEN=>M%AVG_DROP_DEN
AVG_DROP_TMP=>M%AVG_DROP_TMP
AVG_DROP_RAD=>M%AVG_DROP_RAD
D_VAP=>M%D_VAP
RSUM=>M%RSUM
Y_SUM=>M%Y_SUM
Z_SUM=>M%Z_SUM
YY=>M%YY
YYS=>M%YYS
DEL_RHO_D_DEL_Y=>M%DEL_RHO_D_DEL_Y
UVW_GHOST=>M%UVW_GHOST
POIS_PTB=>M%POIS_PTB
POIS_ERR=>M%POIS_ERR
SAVE=>M%SAVE
SAVE2=>M%SAVE2
WORK=>M%WORK
LSAVE=>M%LSAVE
LWORK=>M%LWORK
PRHS=>M%PRHS
BXS=>M%BXS
BXF=>M%BXF 
BYS=>M%BYS
BYF=>M%BYF 
BZS=>M%BZS
BZF=>M%BZF 
BXST=>M%BXST
BXFT=>M%BXFT 
BYST=>M%BYST
BYFT=>M%BYFT 
BZST=>M%BZST
BZFT=>M%BZFT 
LBC=>M%LBC
MBC=>M%MBC
NBC=>M%NBC 
ITRN=>M%ITRN
JTRN=>M%JTRN
KTRN=>M%KTRN
IPS=>M%IPS
U_LEAK=>M%U_LEAK
U_DUCT=>M%U_DUCT
LEAK_AREA=>M%LEAK_AREA
FDS_LEAK_AREA=>M%FDS_LEAK_AREA
D_PBAR_DT=>M%D_PBAR_DT
D_PBAR_S_DT=>M%D_PBAR_S_DT
PBAR=>M%PBAR
PBAR_S=>M%PBAR_S
R_PBAR=>M%R_PBAR
P_0=>M%P_0
RHO_0=>M%RHO_0
TMP_0=>M%TMP_0
PRESSURE_ZONE=>M%PRESSURE_ZONE
PRESSURE_ZONE_WALL=>M%PRESSURE_ZONE_WALL
WORK1=>M%WORK1
WORK2=>M%WORK2
WORK3=>M%WORK3 
WORK4=>M%WORK4
WORK5=>M%WORK5
WORK6=>M%WORK6 
WORK7=>M%WORK7
LOGICAL_WORK=>M%LOGICAL_WORK
WALL_WORK1=>M%WALL_WORK1
WALL_WORK2=>M%WALL_WORK2
QQ=>M%QQ
PP=>M%PP
PPN=>M%PPN
IBK=>M%IBK
IBLK=>M%IBLK
DT=>M%DT
DTOLD=>M%DTOLD
DTNEXT=>M%DTNEXT
DTINT=>M%DTINT
CFL=>M%CFL
DIVMX=>M%DIVMX
VN=>M%VN
RESMAX=>M%RESMAX
DIVMN=>M%DIVMN
ICFL=>M%ICFL
JCFL=>M%JCFL
KCFL=>M%KCFL 
IMX=>M%IMX
JMX=>M%JMX
KMX=>M%KMX
IMN=>M%IMN
JMN=>M%JMN
KMN=>M%KMN
IRM=>M%IRM
JRM=>M%JRM
KRM=>M%KRM
I_VN=>M%I_VN
J_VN=>M%J_VN
K_VN=>M%K_VN
N_EDGES=>M%N_EDGES
IJKE=>M%IJKE
EDGE_INDEX=>M%EDGE_INDEX
TAU_E=>M%TAU_E
OME_E=>M%OME_E
ACTIVE_EDGE=>M%ACTIVE_EDGE
IBAR=>M%IBAR
JBAR=>M%JBAR
KBAR=>M%KBAR 
IBAR2=>M%IBAR2
JBAR2=>M%JBAR2
KBAR2=>M%KBAR2
IBM1=>M%IBM1
JBM1=>M%JBM1
KBM1=>M%KBM1 
IBP1=>M%IBP1
JBP1=>M%JBP1
KBP1=>M%KBP1 
I_LO=>M%I_LO
I_HI=>M%I_HI 
J_LO=>M%J_LO
J_HI=>M%J_HI 
K_LO=>M%K_LO
K_HI=>M%K_HI 
CGI=>M%CGI 
CGI2=>M%CGI2
RGB=>M%RGB
DXI=>M%DXI
DETA=>M%DETA
DZETA=>M%DZETA 
RDXI=>M%RDXI
RDETA=>M%RDETA
RDZETA=>M%RDZETA 
DXMIN=>M%DXMIN
DXMAX=>M%DXMAX 
DYMIN=>M%DYMIN
DYMAX=>M%DYMAX 
DZMIN=>M%DZMIN
DZMAX=>M%DZMAX 
XS=>M%XS 
XF=>M%XF 
YS=>M%YS
YF=>M%YF 
ZS=>M%ZS 
ZF=>M%ZF 
RDXINT=>M%RDXINT
RDYINT=>M%RDYINT
RDZINT=>M%RDZINT 
R=>M%R
RC=>M%RC
X=>M%X
Y=>M%Y
Z=>M%Z 
XC=>M%XC
YC=>M%YC
ZC=>M%ZC
HX=>M%HX
HY=>M%HY
HZ=>M%HZ
DX=>M%DX
DY=>M%DY
DZ=>M%DZ 
DXN=>M%DXN
DYN=>M%DYN
DZN=>M%DZN
RDX=>M%RDX
RDY=>M%RDY
RDZ=>M%RDZ 
RDXN=>M%RDXN
RDYN=>M%RDYN
RDZN=>M%RDZN
CELLSI=>M%CELLSI
CELLSJ=>M%CELLSJ
CELLSK=>M%CELLSK 
RREDX=>M%RREDX
RREDY=>M%RREDY
RREDZ=>M%RREDZ 
RRN=>M%RRN
XPLT=>M%XPLT
YPLT=>M%YPLT
ZPLT=>M%ZPLT 
N_OBST=>M%N_OBST
OBSTRUCTION=>M%OBSTRUCTION
N_VENT=>M%N_VENT
VENTS=>M%VENTS
CELL_INDEX=>M%CELL_INDEX
I_CELL=>M%I_CELL
J_CELL=>M%J_CELL
K_CELL=>M%K_CELL
OBST_INDEX_C=>M%OBST_INDEX_C
WALL_INDEX=>M%WALL_INDEX
SOLID=>M%SOLID 
NWC=>M%NWC
NEWC=>M%NEWC
NDWC=>M%NDWC
CELL_COUNT=>M%CELL_COUNT
WALL_COUNTER=>M%WALL_COUNTER
BC_CLOCK=>M%BC_CLOCK
MASSFLUX=>M%MASSFLUX
RHODW=>M%RHODW
YY_W=>M%YY_W
TMP_F=>M%TMP_F
TMP_B=>M%TMP_B 
HEAT_TRANS_COEF=>M%HEAT_TRANS_COEF
XW=>M%XW
YW=>M%YW
ZW=>M%ZW
TW=>M%TW
AWMPUA=>M%AWMPUA 
AW=>M%AW
WMPUA=>M%WMPUA
WCPUA=>M%WCPUA
RAW=>M%RAW
UW0=>M%UW0
DUWDT=>M%DUWDT
RDN=>M%RDN
MASS_LOSS=>M%MASS_LOSS
EW=>M%EW
KW=>M%KW 
QRADIN=>M%QRADIN
QRADOUT=>M%QRADOUT
QCONF=>M%QCONF
AREA_ADJUST=>M%AREA_ADJUST
RHO_W=>M%RHO_W
TMP_W=>M%TMP_W
RCP_W=>M%RCP_W
RSUM_W=>M%RSUM_W
E_WALL=>M%E_WALL
ACTUAL_BURN_RATE=>M%ACTUAL_BURN_RATE
UW=>M%UW
UWS=>M%UWS
OBST_INDEX_W=>M%OBST_INDEX_W
VENT_INDEX=>M%VENT_INDEX
IJKW=>M%IJKW
INTERPOLATION_FACTOR=>M%INTERPOLATION_FACTOR
CELL_VOLUME_RATIO=>M%CELL_VOLUME_RATIO
BOUNDARY_TYPE=>M%BOUNDARY_TYPE
WALL_INDEX_BACK=>M%WALL_INDEX_BACK
NPPCW=>M%NPPCW
WALL=>M%WALL
OMESH=>M%OMESH
DROPLET =>M%DROPLET  
NLP=>M%NLP 
NLPDIM=>M%NLPDIM
HUMAN =>M%HUMAN  
N_HUMANS=>M%N_HUMANS  
N_HUMANS_DIM=>M%N_HUMANS_DIM
HUMAN_GRID =>M%HUMAN_GRID
N_SLCF=>M%N_SLCF
SLICE=>M%SLICE
INC=>M%INC
NPATCH=>M%NPATCH
UIID=>M%UIID 
RAD_CALL_COUNTER=>M%RAD_CALL_COUNTER
ANGLE_INC_COUNTER=>M%ANGLE_INC_COUNTER
RHO_AVG=>M%RHO_AVG
Q_UPPER=>M%Q_UPPER
INTERPOLATED_MESH => M%INTERPOLATED_MESH
STRING=>M%STRING 
N_STRINGS=>M%N_STRINGS 
N_STRINGS_MAX=>M%N_STRINGS_MAX
 
END SUBROUTINE POINT_TO_MESH

SUBROUTINE GET_REV_mesh(MODULE_REV,MODULE_DATE)
INTEGER,INTENT(INOUT) :: MODULE_REV
CHARACTER(255),INTENT(INOUT) :: MODULE_DATE

WRITE(MODULE_DATE,'(A)') meshrev(INDEX(meshrev,':')+1:LEN_TRIM(meshrev)-2)
READ (MODULE_DATE,'(I5)') MODULE_REV
WRITE(MODULE_DATE,'(A)') meshdate

END SUBROUTINE GET_REV_mesh

 
END MODULE MESH_POINTERS
