MODULE PRECISION_PARAMETERS
 
! Set the parameters for ``single'' and ``double'' precision
 
IMPLICIT NONE
 
INTEGER, PARAMETER :: FB = SELECTED_REAL_KIND(6)
INTEGER, PARAMETER :: EB = SELECTED_REAL_KIND(12)
CHARACTER(255), PARAMETER :: precid='$Id: prec.f90,v 1.4 2007/01/04 19:22:36 dr_jfloyd Exp $'
 
END MODULE PRECISION_PARAMETERS
 
