MODULE PRECISION_PARAMETERS
 
! Set the parameters for ``single'' and ``double'' precision
 
IMPLICIT NONE
 
INTEGER, PARAMETER :: FB = SELECTED_REAL_KIND(6)
INTEGER, PARAMETER :: EB = SELECTED_REAL_KIND(12)
CHARACTER(255), PARAMETER :: precid='$Id$'
 
END MODULE PRECISION_PARAMETERS
 
