@echo off
:: set fds=call ..\..\..\bin\fds_db
set fds=..\..\FDS_Compilation\intel_win_64\fds_win_64
%fds% geom_arch.fds
%fds% geom_azim.fds
%fds% geom_elev.fds
%fds% geom_obst.fds
%fds% geom_scale.fds
%fds% geom_simple.fds
%fds% geom_sphere.fds
%fds% geom_sphere2.fds
%fds% geom_terrain.fds
%fds% geom_texture.fds
%fds% geom_texture2.fds
%fds% geom_texture3.fds
%fds% geom_time.fds
%fds% geom_time2.fds
%fds% geom_time3.fds
%fds% geom_time4.fds
%fds% geom_time5.fds
